apiVersion: apps/v1
kind: Deployment
metadata:
  name: kirito-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kirito
  template:
    metadata:
      labels:
        app: kirito
    spec:
      containers:
        - name: kirito
          image: iodinehanifan/kirito:v2
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080  
